---
- name: eror handling command use
  hosts: all
  become: yes
  tasks: 

  - name: installing git
    yum: 
     name: git
     state: present
    tags: "pkg"
     # ignore_errors: yes

  - name: installing docker
    yum:
     name: ['docker', 'git', 'mysql']
     state: absentt
    ignore_errors: yes

  - name: installing httpd
    yum:
     name: httpd
     state: installed
     # tags: pkg
